syntax = "proto3";

// Categoria: 16_social
// Total: 15 segments

// Enum: enum proto.ESocial.PlayerBattleTagID
enum PlayerBattleTagID {
    PlayerBattleTagID_BESTPARTNER = 1103;
    PlayerBattleTagID_RAMPAGE = 1109;
    PlayerBattleTagID_LEADER = 1110;
    PlayerBattleTagID_NONE = 0;
    PlayerBattleTagID_UNCROWN = 1102;
    PlayerBattleTagID_PEACEMAKER = 1106;
    PlayerBattleTagID_SNIPER = 1104;
    PlayerBattleTagID_SHORTSTOP = 1108;
    PlayerBattleTagID_DOMINATION = 1101;
    PlayerBattleTagID_AMBUSH = 1107;
    PlayerBattleTagID_MELEE = 1105;
}

// Enum: enum proto.ESocial.PlayerBattleTagCdtType
enum PlayerBattleTagCdtType {
    PlayerBattleTagCdtType_BR_ASSIST_SMALLER = 100702;
    PlayerBattleTagCdtType_CS_DAMAGE_PER_ROUND_SMALLER = 200602;
    PlayerBattleTagCdtType_CS_DAMAGE_MAX = 200301;
    PlayerBattleTagCdtType_CS_DEATH_PER_ROUND_SMALLER = 200402;
    PlayerBattleTagCdtType_BR_DISTANCE_LARGER = 101001;
    PlayerBattleTagCdtType_BR_QuadraKill_LARGER = 101102;
    PlayerBattleTagCdtType_CS_DAMAGE_PER_ROUND_LARGER = 200601;
    PlayerBattleTagCdtType_BR_KILL_LARGER = 100501;
    PlayerBattleTagCdtType_CS_DISTANCE_LARGER = 201001;
    PlayerBattleTagCdtType_CS_REVIVE_PER_ROUND_SMALLER = 200802;
    PlayerBattleTagCdtType_CS_WinAverageKill_SMALLER = 201302;
    PlayerBattleTagCdtType_CS_FirstBlood_LARGER = 201401;
    PlayerBattleTagCdtType_NONE = 0;
    PlayerBattleTagCdtType_BR_KILL_SMALLER = 100502;
    PlayerBattleTagCdtType_CS_KILL_MAX = 200201;
    PlayerBattleTagCdtType_CS_ASSIST_PER_ROUND_SMALLER = 200702;
    PlayerBattleTagCdtType_BR_REVIVE_SMALLER = 100802;
    PlayerBattleTagCdtType_BR_RANK_SMALLER = 100102;
    PlayerBattleTagCdtType_BR_LAST_ELIMINATED = 100201;
    PlayerBattleTagCdtType_BR_DAMAGE_SMALLER = 100602;
    PlayerBattleTagCdtType_BR_ASSIST_LARGER = 100701;
    PlayerBattleTagCdtType_CS_KILL_PER_ROUND_SMALLER = 200502;
    PlayerBattleTagCdtType_BR_TripleKill_LARGER = 101101;
    PlayerBattleTagCdtType_BR_DISTANCE_LARGER_PER_MINIUE = 100901;
    PlayerBattleTagCdtType_BR_DISTANCE_SMALLER_PER_MINIUE = 100902;
    PlayerBattleTagCdtType_CS_KILL_PER_ROUND_LARGER = 200501;
    PlayerBattleTagCdtType_BR_DISTANCE_SMALLER = 101002;
    PlayerBattleTagCdtType_BR_DAMAGE_LARGER = 100601;
    PlayerBattleTagCdtType_CS_WIN = 200101;
    PlayerBattleTagCdtType_BR_RANK_LARGER = 100101;
    PlayerBattleTagCdtType_CS_DISTANCE_SMALLER = 201002;
    PlayerBattleTagCdtType_CS_WinAverageKill_LARGER = 201301;
    PlayerBattleTagCdtType_BR_REVIVE_LARGER = 100801;
    PlayerBattleTagCdtType_CS_REVIVE_PER_ROUND_LARGER = 200801;
    PlayerBattleTagCdtType_CS_MVP_LARGER = 201501;
    PlayerBattleTagCdtType_CS_DEATH_PER_ROUND_LARGER = 200401;
    PlayerBattleTagCdtType_CS_ASSIST_PER_ROUND_LARGER = 200701;
}

// Enum: enum proto.ESocial.SocialTag
enum SocialTag {
    SocialTag_VETERAN = 2103;
    SocialTag_FASHION = 2101;
    SocialTag_VOICEON = 2107;
    SocialTag_VOICEOFF = 2108;
    SocialTag_PLAYFORFUN = 2106;
    SocialTag_PLAYFORWIN = 2105;
    SocialTag_NEWBIE = 2104;
    SocialTag_NONE = 0;
    SocialTag_SOCIAL = 2102;
}

// Enum: enum proto.ESocial.Gender
enum Gender {
    Gender_FEMALE = 2;
    Gender_NONE = 0;
    Gender_MALE = 1;
    Gender_UNLIMITED = 999;
}

// Enum: enum proto.ESocial.Language
enum Language {
    Language_CN_SIMPLIFIED = 2;
    Language_SPANISH = 8;
    Language_INDONESIAN = 6;
    Language_JAPANESE = 15;
    Language_BURMESE = 18;
    Language_ROMANIAN = 16;
    Language_HINDI = 14;
    Language_Thai = 4;
    Language_RUSSIAN = 9;
    Language_URDU = 19;
    Language_CN_TRADITIONAL = 3;
    Language_TURKISH = 13;
    Language_KOREAN = 10;
    Language_PORTUGUESE = 7;
    Language_EN = 1;
    Language_GERMAN = 12;
    Language_VIETNAMESE = 5;
    Language_NONE = 0;
    Language_ARABIC = 17;
    Language_FRENCH = 11;
    Language_UNLIMITED = 999;
}

// Enum: enum proto.ESocial.RankShow
enum RankShow {
    RankShow_CS = 2;
    RankShow_NONE = 0;
    RankShow_BR = 1;
    RankShow_UNLIMITED = 999;
}

// Enum: enum proto.ESocial.TimeOnline
enum TimeOnline {
    TimeOnline_WEEKEND = 2;
    TimeOnline_WORKDAY = 1;
    TimeOnline_NONE = 0;
    TimeOnline_UNLIMITED = 999;
}

// Enum: enum proto.ESocial.TimeActive
enum TimeActive {
    TimeActive_MORNING = 1;
    TimeActive_NIGHT = 3;
    TimeActive_NONE = 0;
    TimeActive_UNLIMITED = 999;
    TimeActive_AFTERNOON = 2;
}

// Enum: enum proto.ESocial.ModePrefer
enum ModePrefer {
    ModePrefer_CS = 2;
    ModePrefer_BR = 1;
    ModePrefer_NONE = 0;
    ModePrefer_ENTERTAINMENT = 3;
    ModePrefer_UNLIMITED = 999;
}

// Message: proto.ESocial
message ESocial {
    // Sem campos definidos no dump
}

// Message: proto.SocialBasicInfo
message SocialBasicInfo {
    System_UInt64 account_id = 1;
    proto_ESocial_Gender gender = 2;
    proto_ESocial_Language language = 3;
    proto_ESocial_TimeOnline time_online = 4;
    proto_ESocial_TimeActive time_active = 5;
    repeated proto_ESocial_PlayerBattleTagID battle_tag = 6;
    repeated proto_ESocial_SocialTag social_tag = 7;
    proto_ESocial_ModePrefer mode_prefer = 8;
    System_String signature = 9;
    proto_ESocial_RankShow rank_show = 10;
    repeated System_UInt32 battle_tag_count = 11;
}

// Message: proto.CSSocialBasicInfoRes
message CSSocialBasicInfoRes {
    proto_SocialBasicInfo info = 1;
}

// Message: proto.CSUpdateSocialBasicInfoReq
message CSUpdateSocialBasicInfoReq {
    proto_ESocial_Gender gender = 1;
    proto_ESocial_Language language = 2;
    proto_ESocial_TimeOnline time_online = 3;
    proto_ESocial_TimeActive time_active = 4;
    repeated proto_ESocial_PlayerBattleTagID battle_tag = 5;
    repeated proto_ESocial_SocialTag social_tag = 6;
    proto_ESocial_ModePrefer mode_prefer = 7;
    System_String signature = 8;
    proto_ESocial_RankShow rank_show = 9;
}

// Message: proto.CSGetBattleTagRes
message CSGetBattleTagRes {
    repeated proto_BattleTagCount battle_tag_counts = 1;
    repeated System_UInt32 show_tag_ids = 2;
}

// Message: proto.BattleTagCount
message BattleTagCount {
    System_UInt32 tag_id = 1;
    System_UInt32 count = 2;
}

